name: CorePlugin
main: core.CorePlugin
version: 1.0
commands:
  help:
    description: Help command
    usage: /<command>
  honor:
    description: 'The root command for the Honor Points Plugin'
    usage: '/<command> put bullshit here'
    permission-message: 'You don''t have <permission>'
  kit:
    description: Grab a kit
    usage: /<command>
  who:
    description: 'Lists who is online'
    usage: /<command>
  coresave:
    description: 'Forces a server save'
    usage: /<command

permissions:
  honor.manipulate:
    description: Gives access to /honor (add/give), /honor (take/deduct), and /honor set
    default: op

  honor.view.*:
    description: Gives access to all honor viewing commands
    default: op
    children:
      honor.view.other: true
      honor.view.self: true
  honor.view.other:
    description: Gives access to /honor (view/see)
    default: op
  honor.view.self:
    description: Gives access to /honor
    default: true
    
  core.utility.select:
    description: Lets players select blocks with sticks
    default: op
    
  core.override.drop:
    description: Lets players drop items regardless of drop blocking
    default: op
  core.override.place:
    description: Lets players place blocks regardless of block place restrictions
    default: op
    
  core.forcesave:
    description: Allows a force save of the server
    default: op